# GPU 环境需要CUDA 11.1，cudnn8
# docker 运行需要nvidia-docker环境
FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04

RUN apt update
RUN apt upgrade -y

# 配置nighres运行环境
# 解决tzdata安装需要交互的问题, tzdata是安装openjdk-11-jdk的必要组件
ENV DEBIAN_FRONTEND=noninteractive
RUN apt install tzdata -y
# java运行环境
RUN apt install openjdk-11-jdk -y
RUN apt install python3 python3-pip -y
RUN pip3 install nighres
ENV LD_LIBRARY_PATH=/usr/lib/jvm/java-11-openjdk-amd64/lib:/usr/lib/jvm/java-11-openjdk-amd64/lib/server

# FastCSR 执行环境
RUN pip3 install -U numpy
RUN pip3 install antspyx
RUN pip3 install sh

# nnUNet 执行环境
RUN pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install nnunet==1.7.0

# 拷贝模型及脚本
COPY ./model/ /root/FastCSR/model/
COPY ./*.py /root/FastCSR/

# 设置容器启动点
ENTRYPOINT ["python3","/root/FastCSR/pipeline.py"]