# GPU 环境需要CUDA 11.8，cudnn8
# docker 运行需要nvidia-docker环境
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

RUN apt-get update && apt-get upgrade -y

# 配置nighres运行环境
# 解决tzdata安装需要交互的问题, tzdata是安装openjdk-11-jdk的必要组件
ENV DEBIAN_FRONTEND=noninteractive
RUN apt install tzdata -y
# java运行环境
RUN apt install openjdk-11-jdk -y
ENV LD_LIBRARY_PATH=/usr/lib/jvm/java-11-openjdk-amd64/lib:/usr/lib/jvm/java-11-openjdk-amd64/lib/server
# nighres
RUN apt install python3 python3-pip -y
RUN python3 -m pip install -U pip
COPY ./nighres-1.5.0-cp38-cp38-linux_x86_64.whl /opt/nighres-1.5.0-cp38-cp38-linux_x86_64.whl
RUN pip3 install /opt/nighres-1.5.0-cp38-cp38-linux_x86_64.whl

# FastCSR 执行环境
RUN pip3 install numpy
RUN pip3 install antspyx
RUN pip3 install sh

# nnUNet 执行环境
RUN pip3 install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install nnunet==1.7.1

# 拷贝模型及脚本
COPY ./model/ /root/FastCSR/model/
COPY ./*.py /root/FastCSR/

# 设置容器启动点
ENTRYPOINT ["python3","/root/FastCSR/pipeline.py"]